# Generated by Django 2.2.3 on 2019-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
